stores:
  - store_id: self_honten
    name: むつ本店
    type: self
    url: https://www.carsensor.net/shop/aomori/307548001/stocklist/

  - store_id: competitor_a
    name: 十和田店
    type: competitor
    url: https://www.carsensor.net/shop/aomori/307548002/stocklist/

  - store_id: competitor_b
    name: ダンク
    type: competitor
    url: https://www.carsensor.net/shop/aomori/307117002/stocklist/
